package com.mit.entity;

// Generated 23 mai 2016 00:14:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contratsociete generated by hbm2java
 */
@Entity
@Table(name = "contratsociete", catalog = "mitdb")
public class Contratsociete implements java.io.Serializable {

	private ContratsocieteId id;
	private Societe societe;
	private Contrat contrat;
	private Projet projet;
	private Integer coutPayer;

	public Contratsociete() {
	}

	public Contratsociete(ContratsocieteId id, Societe societe,
			Contrat contrat, Projet projet) {
		this.id = id;
		this.societe = societe;
		this.contrat = contrat;
		this.projet = projet;
	}

	public Contratsociete(ContratsocieteId id, Societe societe,
			Contrat contrat, Projet projet, Integer coutPayer) {
		this.id = id;
		this.societe = societe;
		this.contrat = contrat;
		this.projet = projet;
		this.coutPayer = coutPayer;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProjet", column = @Column(name = "idProjet", nullable = false)),
			@AttributeOverride(name = "idContrat", column = @Column(name = "idContrat", nullable = false)),
			@AttributeOverride(name = "idSociete", column = @Column(name = "idSociete", nullable = false)) })
	public ContratsocieteId getId() {
		return this.id;
	}

	public void setId(ContratsocieteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSociete", nullable = false, insertable = false, updatable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idContrat", nullable = false, insertable = false, updatable = false)
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false, insertable = false, updatable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "coutPayer", precision = 8, scale = 0)
	public Integer getCoutPayer() {
		return this.coutPayer;
	}

	public void setCoutPayer(Integer coutPayer) {
		this.coutPayer = coutPayer;
	}

}
