package com.mit.entity;

// Generated 23 mai 2016 00:14:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "mitdb")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private Date dateContrat;
	private Date debutContrat;
	private Date finContrat;
	private Set<Contratsociete> contratsocietes = new HashSet<Contratsociete>(0);
	private Set<Contratmembre> contratmembres = new HashSet<Contratmembre>(0);

	public Contrat() {
	}

	public Contrat(Date dateContrat, Date debutContrat, Date finContrat,
			Set<Contratsociete> contratsocietes,
			Set<Contratmembre> contratmembres) {
		this.dateContrat = dateContrat;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
		this.contratsocietes = contratsocietes;
		this.contratmembres = contratmembres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idContrat", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateContrat", length = 10)
	public Date getDateContrat() {
		return this.dateContrat;
	}

	public void setDateContrat(Date dateContrat) {
		this.dateContrat = dateContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutContrat", length = 10)
	public Date getDebutContrat() {
		return this.debutContrat;
	}

	public void setDebutContrat(Date debutContrat) {
		this.debutContrat = debutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finContrat", length = 10)
	public Date getFinContrat() {
		return this.finContrat;
	}

	public void setFinContrat(Date finContrat) {
		this.finContrat = finContrat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Set<Contratsociete> getContratsocietes() {
		return this.contratsocietes;
	}

	public void setContratsocietes(Set<Contratsociete> contratsocietes) {
		this.contratsocietes = contratsocietes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Set<Contratmembre> getContratmembres() {
		return this.contratmembres;
	}

	public void setContratmembres(Set<Contratmembre> contratmembres) {
		this.contratmembres = contratmembres;
	}

}
