package com.mit.entity;

// Generated 23 mai 2016 00:14:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cv generated by hbm2java
 */
@Entity
@Table(name = "cv", catalog = "mitdb")
public class Cv implements java.io.Serializable {

	private Integer idCv;
	private Set<Diplome> diplomes = new HashSet<Diplome>(0);
	private Set<Experience> experiences = new HashSet<Experience>(0);
	private Set<Competance> competances = new HashSet<Competance>(0);
	private Set<Membre> membres = new HashSet<Membre>(0);

	public Cv() {
	}

	public Cv(Set<Diplome> diplomes, Set<Experience> experiences,
			Set<Competance> competances, Set<Membre> membres) {
		this.diplomes = diplomes;
		this.experiences = experiences;
		this.competances = competances;
		this.membres = membres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCv", unique = true, nullable = false)
	public Integer getIdCv() {
		return this.idCv;
	}

	public void setIdCv(Integer idCv) {
		this.idCv = idCv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Diplome> getDiplomes() {
		return this.diplomes;
	}

	public void setDiplomes(Set<Diplome> diplomes) {
		this.diplomes = diplomes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Experience> getExperiences() {
		return this.experiences;
	}

	public void setExperiences(Set<Experience> experiences) {
		this.experiences = experiences;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "cvs")
	public Set<Competance> getCompetances() {
		return this.competances;
	}

	public void setCompetances(Set<Competance> competances) {
		this.competances = competances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cv")
	public Set<Membre> getMembres() {
		return this.membres;
	}

	public void setMembres(Set<Membre> membres) {
		this.membres = membres;
	}

}
