package com.mit.entity;

// Generated 23 mai 2016 00:14:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "mitdb")
public class Experience implements java.io.Serializable {

	private Integer idExp;
	private Cv cv;
	private String poste;
	private Date dateDeb;
	private Date dateFin;

	public Experience() {
	}

	public Experience(Cv cv, String poste, Date dateDeb, Date dateFin) {
		this.cv = cv;
		this.poste = poste;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idExp", unique = true, nullable = false)
	public Integer getIdExp() {
		return this.idExp;
	}

	public void setIdExp(Integer idExp) {
		this.idExp = idExp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCv")
	public Cv getCv() {
		return this.cv;
	}

	public void setCv(Cv cv) {
		this.cv = cv;
	}

	@Column(name = "poste", length = 254)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDeb", length = 10)
	public Date getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(Date dateDeb) {
		this.dateDeb = dateDeb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateFin", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
