package com.mit.entity;

// Generated 23 mai 2016 00:14:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pvreunion generated by hbm2java
 */
@Entity
@Table(name = "pvreunion", catalog = "mitdb")
public class Pvreunion implements java.io.Serializable {

	private Integer idReunion;
	private String objetReunion;
	private Date dateReunion;
	private String contenu;
	private Set<Contratmembre> contratmembres = new HashSet<Contratmembre>(0);

	public Pvreunion() {
	}

	public Pvreunion(String objetReunion, Date dateReunion, String contenu,
			Set<Contratmembre> contratmembres) {
		this.objetReunion = objetReunion;
		this.dateReunion = dateReunion;
		this.contenu = contenu;
		this.contratmembres = contratmembres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idReunion", unique = true, nullable = false)
	public Integer getIdReunion() {
		return this.idReunion;
	}

	public void setIdReunion(Integer idReunion) {
		this.idReunion = idReunion;
	}

	@Column(name = "objetReunion", length = 254)
	public String getObjetReunion() {
		return this.objetReunion;
	}

	public void setObjetReunion(String objetReunion) {
		this.objetReunion = objetReunion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReunion", length = 10)
	public Date getDateReunion() {
		return this.dateReunion;
	}

	public void setDateReunion(Date dateReunion) {
		this.dateReunion = dateReunion;
	}

	@Column(name = "contenu", length = 254)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvreunion")
	public Set<Contratmembre> getContratmembres() {
		return this.contratmembres;
	}

	public void setContratmembres(Set<Contratmembre> contratmembres) {
		this.contratmembres = contratmembres;
	}

}
